package com.github.beastyboo.advancedjail.domain;

/**
 * Created by Torbie on 16.12.2020.
 */
public enum MessageType {
    PLAYER_NOT_FOUND,
    PLAYER_OUTSIDE_CELL,
    PLAYER_ALREADY_JAILED,
    PLAYER_ALREADY_HANDCUFFED,
    PLAYER_HANDCUFFED_ADDED,
    PLAYER_HANDCUFFED_REMOVED,
    PLAYER_ARREST,
    PLAYER_RELEASE ,
    PLAYER_NOT_HANDCUFFED,
    PLAYER_WRONG_KEY,

    TARGET_HANDCUFF_ADDED,
    TARGET_HANDCUFF_REMOVED,
    TARGET_ARREST,
    TARGET_RELEASE,

    JAIL_NOT_FOUND,
    JAIL_ALREADY_EXIST,
    JAIL_REGIONNAME_ALREADY_EXIST,
    JAIL_CREATED,
    JAIL_DELETED,
    JAIL_RELEASE_POINT_CREATED,
    JAIL_LIST_EMPTY,
    JAIL_CELL_LIST_EMPTY,
    JAIL_INMATE_LIST_EMPTY,

    CELL_NAME_TAKEN,
    CELL_SIZE_INVALID,
    CELL_CREATED,
    CELL_NOT_FOUND,
    CELL_IS_FULL,
    CELL_DELETED,

    HANDCUFF_NOT_FOUND,
    HANDCUFF_GIVEN,

    INMATE_NOT_FOUND,
    INMATE_ALREADY_EXIST,
    INMATE_BILL_NOT_LOADED,
    INMATE_BROADCAST_NOT_LOADED,
    INMATE_NOT_ENOUGH_MONEY,
    INMATE_STILL_IN_COOLDOWN,
    INMATE_BROADCAST_ITEM_USED,
    INMATE_BROADCAST_SENT,
    INMATE_RELEASE_BROADCAST,
    INMATE_ESCAPE_BROADCAST,

    KEY_NOT_FOUND,
    KEY_GIVEN;
}
